dist: trusty
sudo: required
language: go
go: 1.6

env:
  global:
  - GOPATH=$HOME/go

before_install:
  - ./script/upgrade-docker

install:
  - script/bootstrap
script:
  - script/test
  - script/compose
  - script/compose-test

notifications:
  email: false
  slack: false

branches:
  only:
  - master
